/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Manufacturer
 * Id: 4ce421e9-c403-eee8-fdc2-74f09392a749
 * Codename: manufacturer
 */
export type Manufacturer = 'aerobie' | 'espro' | 'hario' | 'chemex';
