/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Product status
 * Id: 79b1c5b6-30bc-d076-a236-d9ec9f1ff01b
 * Codename: product_status
 */
export type ProductStatus = 'bestseller' | 'on_sale';
