/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Sitemap
 * Id: 538125ff-c59c-4193-88ce-71a7016830ed
 * Codename: sitemap_538125f
 */
export type Sitemap =
  | 'about_us'
  | 'accessories'
  | 'articles'
  | 'australia'
  | 'brewers'
  | 'cafes'
  | 'coffee'
  | 'europe'
  | 'grinders'
  | 'home'
  | 'north_america'
  | 'offices'
  | 'products';
