import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Guidelines for content creators
 * Id: 83639954-da29-4743-b11d-0949069d399f
 * Codename: guidelines_for_content_creators
 */
export type GuidelinesForContentCreators = IContentItem<{}>;
