/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Project name: Sample Project
 * Environment: Production
 * Project Id: 67a80a94-d137-00ae-280a-3c8625c4e19b
 */
export const webhooks = {} as const;
