import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type GuidelinesForContentCreators } from '../content-type-snippets/guidelines_for_content_creators';
import { type Metadata } from '../content-type-snippets/metadata';
import { type Processing } from '../taxonomies/processing';
import { type ProductStatus } from '../taxonomies/product_status';
import { type Sitemap } from '../taxonomies/sitemap_538125f';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Coffee
 * Id: 929985ac-4aa5-436b-85a2-94c2d4fbbebd
 * Codename: coffee
 */
export type Coffee = IContentItem<{
  /**
   * Altitude (text)
   * Required: false
   * Id: 23a772c0-0b2b-588d-9849-e29068701f03
   * Codename: altitude
   *
   * Include the altitude at which the coffee is grown. Elevation affects the size, shape, and taste of coffee beans.
   */
  altitude: Elements.TextElement;

  /**
   * Country (text)
   * Required: false
   * Id: 6eec1918-378d-3b15-8b1a-19c5f0748321
   * Codename: country
   *
   * Include  the coffee's country of origin.
   */
  country: Elements.TextElement;

  /**
   * Farm (text)
   * Required: false
   * Id: e5cf103f-9b84-1ab0-29f1-fb5a1657c6f7
   * Codename: farm
   *
   * Include the name of the coffee farm.
   */
  farm: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 30ac3ccc-1e7f-1490-e1f6-915c64176a55
   * Codename: image
   *
   * Upload a product image; the recommended size is 300 × 300 px.
   */
  image: Elements.AssetsElement;

  /**
   * Long description (rich_text)
   * Required: false
   * Id: d468a0aa-e0fa-0cae-41db-6e006bff2527
   * Codename: long_description
   *
   * Include a full product description.
   */
  longDescription: Elements.RichTextElement;

  /**
   * Price (number)
   * Required: false
   * Id: 624592dc-49b2-330a-7185-e1f2396ce90c
   * Codename: price
   *
   * Include a product price.
   */
  price: Elements.NumberElement;

  /**
   * Processing (taxonomy)
   * Required: false
   * Id: b63e3516-d5fa-fdac-a03a-2b027bf02a28
   * Codename: processing
   */
  processing: Elements.TaxonomyElement<Processing>;

  /**
   * Product name (text)
   * Required: false
   * Id: edaec5c4-e653-9109-eb0d-fc40ccf3c810
   * Codename: product_name
   *
   * Include a product display name.
   */
  productName: Elements.TextElement;

  /**
   * Product status (taxonomy)
   * Required: false
   * Id: 1ee64175-fde7-fc1e-5259-511a31c326c3
   * Codename: product_status
   *
   * Add a product status if the product is included in a special offering.
   */
  productStatus: Elements.TaxonomyElement<ProductStatus>;

  /**
   * Short description (rich_text)
   * Required: false
   * Id: b5a3263a-a1d7-92b7-865a-329f833285fa
   * Codename: short_description
   *
   * Include a short description that fits within 160 characters.
   */
  shortDescription: Elements.RichTextElement;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: 99d7a378-e18f-41dd-b5bb-2a569c3d1de7
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;

  /**
   * URL pattern (url_slug)
   * Required: false
   * Id: 3af8ce38-c03d-063c-ea80-72684dfddf31
   * Codename: url_pattern
   *
   * Provide a SEO-friendly URL.
   */
  urlPattern: Elements.UrlSlugElement;

  /**
   * Variety (text)
   * Required: false
   * Id: 301c6712-962f-b05a-6f6e-2f0e1e959039
   * Codename: variety
   *
   * Include a coffee variety name.
   */
  variety: Elements.TextElement;
}> &
  GuidelinesForContentCreators &
  Metadata;
