import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type GuidelinesForContentCreators } from '../content-type-snippets/guidelines_for_content_creators';
import { type Sitemap } from '../taxonomies/sitemap_538125f';

/**
 * Generated by '@kontent-ai/model-generator@5.8.0'
 *
 * Fact about us
 * Id: b99ec220-0f2b-4658-a080-ff0afe92f6d1
 * Codename: fact_about_us
 */
export type FactAboutUs = IContentItem<{
  /**
   * Description (rich_text)
   * Required: false
   * Id: 1b658e81-88c9-73d1-374d-7a60e3756ef7
   * Codename: description
   *
   * Include a main goal of our business. The limit is 80 characters.
   */
  description: Elements.RichTextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 68d194b6-efad-6b25-89a4-2dfc75fed5a5
   * Codename: image
   *
   * Attach a teaser image; max. dimensions are 1280 × 600 px; allowed formats are *.jpg, *.png, *.gif.
   */
  image: Elements.AssetsElement;

  /**
   * Sitemap (taxonomy)
   * Required: false
   * Id: 23a715f9-755c-4b9d-b6b3-e02fc1b09b83
   * Codename: sitemap
   */
  sitemap: Elements.TaxonomyElement<Sitemap>;

  /**
   * Title (text)
   * Required: false
   * Id: 2375ca8a-43d2-7282-162c-922a6fdeba3e
   * Codename: title
   *
   * Provide a title that fits within 60 characters.
   */
  title: Elements.TextElement;
}> &
  GuidelinesForContentCreators;
